# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_files/game_size.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameSize(object):
    def setupUi(self, GameSize):
        GameSize.setObjectName("GameSize")
        GameSize.setWindowModality(QtCore.Qt.WindowModal)
        GameSize.resize(465, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(GameSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.main_widget = QtWidgets.QWidget(GameSize)
        self.main_widget.setObjectName("main_widget")
        self.main_layout.addWidget(self.main_widget)
        self.side_layout = QtWidgets.QWidget(GameSize)
        self.side_layout.setMaximumSize(QtCore.QSize(190, 16777215))
        self.side_layout.setObjectName("side_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_layout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.side_layout)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.beginner_option = QtWidgets.QRadioButton(self.side_layout)
        self.beginner_option.setObjectName("beginner_option")
        self.verticalLayout_4.addWidget(self.beginner_option)
        self.medium_option = QtWidgets.QRadioButton(self.side_layout)
        self.medium_option.setObjectName("medium_option")
        self.verticalLayout_4.addWidget(self.medium_option)
        self.expert_option = QtWidgets.QRadioButton(self.side_layout)
        self.expert_option.setObjectName("expert_option")
        self.verticalLayout_4.addWidget(self.expert_option)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.main_layout.addWidget(self.side_layout)
        self.horizontalLayout.addLayout(self.main_layout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(GameSize)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GameSize)
        self.buttonBox.accepted.connect(GameSize.accept)
        self.buttonBox.rejected.connect(GameSize.reject)
        QtCore.QMetaObject.connectSlotsByName(GameSize)

    def retranslateUi(self, GameSize):
        _translate = QtCore.QCoreApplication.translate
        GameSize.setWindowTitle(_translate("GameSize", "Game Size"))
        self.logo.setText(_translate("GameSize", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Game Size</span></p></body></html>"))
        self.beginner_option.setText(_translate("GameSize", "Beginner (7 x 7)"))
        self.medium_option.setText(_translate("GameSize", "Medium (13 x 13)"))
        self.expert_option.setText(_translate("GameSize", "Expert (19 x 19)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameSize = QtWidgets.QDialog()
    ui = Ui_GameSize()
    ui.setupUi(GameSize)
    GameSize.show()
    sys.exit(app.exec_())
