# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Game Size.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameSize(object):
    def setupUi(self, GameSize):
        GameSize.setObjectName("GameSize")
        GameSize.resize(556, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(GameSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(GameSize)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_widget = QtWidgets.QWidget(self.widget)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout_3.addWidget(self.main_widget)
        self.sidebar_widget = QtWidgets.QWidget(self.widget)
        self.sidebar_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar_widget.setObjectName("sidebar_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sidebar_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.sidebar_widget)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.beginner_btn = QtWidgets.QRadioButton(self.sidebar_widget)
        self.beginner_btn.setObjectName("beginner_btn")
        self.verticalLayout_4.addWidget(self.beginner_btn)
        self.medium_btn = QtWidgets.QRadioButton(self.sidebar_widget)
        self.medium_btn.setObjectName("medium_btn")
        self.verticalLayout_4.addWidget(self.medium_btn)
        self.expert_btn = QtWidgets.QRadioButton(self.sidebar_widget)
        self.expert_btn.setObjectName("expert_btn")
        self.verticalLayout_4.addWidget(self.expert_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addWidget(self.sidebar_widget)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(GameSize)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GameSize)
        self.buttonBox.accepted.connect(GameSize.accept)
        self.buttonBox.rejected.connect(GameSize.reject)
        QtCore.QMetaObject.connectSlotsByName(GameSize)

    def retranslateUi(self, GameSize):
        _translate = QtCore.QCoreApplication.translate
        GameSize.setWindowTitle(_translate("GameSize", "Game Size"))
        self.logo.setText(_translate("GameSize", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Game Type</span></p></body></html>"))
        self.beginner_btn.setText(_translate("GameSize", "Beginner (7 x 7)"))
        self.medium_btn.setText(_translate("GameSize", "Medium ( 13 x 13 )"))
        self.expert_btn.setText(_translate("GameSize", "Expert ( 19 x 19 )"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameSize = QtWidgets.QDialog()
    ui = Ui_GameSize()
    ui.setupUi(GameSize)
    GameSize.show()
    sys.exit(app.exec_())
