# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(637, 434)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Help)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideBar_widget = QtWidgets.QWidget(Help)
        self.sideBar_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sideBar_widget.setStyleSheet("")
        self.sideBar_widget.setObjectName("sideBar_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sideBar_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.about_btn = QtWidgets.QPushButton(self.sideBar_widget)
        self.about_btn.setObjectName("about_btn")
        self.verticalLayout_3.addWidget(self.about_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.shortcuts_btn = QtWidgets.QPushButton(self.sideBar_widget)
        self.shortcuts_btn.setObjectName("shortcuts_btn")
        self.verticalLayout_3.addWidget(self.shortcuts_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.team_btn = QtWidgets.QPushButton(self.sideBar_widget)
        self.team_btn.setObjectName("team_btn")
        self.verticalLayout_3.addWidget(self.team_btn)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.sideBar_widget)
        self.mainBar_widget = QtWidgets.QWidget(Help)
        self.mainBar_widget.setObjectName("mainBar_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainBar_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.heading = QtWidgets.QLabel(self.mainBar_widget)
        self.heading.setMaximumSize(QtCore.QSize(16777215, 70))
        self.heading.setObjectName("heading")
        self.verticalLayout.addWidget(self.heading)
        self.help_text = QtWidgets.QLabel(self.mainBar_widget)
        self.help_text.setStyleSheet("")
        self.help_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.help_text.setTextFormat(QtCore.Qt.RichText)
        self.help_text.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.help_text.setObjectName("help_text")
        self.verticalLayout.addWidget(self.help_text)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.mainBar_widget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Form"))
        self.about_btn.setText(_translate("Help", "About"))
        self.shortcuts_btn.setText(_translate("Help", "Shortcuts"))
        self.team_btn.setText(_translate("Help", "Team"))
        self.heading.setText(_translate("Help", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Help</span></p></body></html>"))
        self.help_text.setText(_translate("Help", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">This is about us</span></p></body></html>"))

    def helpMenu(self):
        userGuide = """Go("encircling game") is an abstract strategy board game for two players, in which the aim is to surround more territory than the opponent.The game was invented in China over 3, 000 years ago and is therefore believed to be the oldest board game continuously played today.It was considered one of the four essential arts of the cultured aristocratic Chinese scholars in antiquity.Despite its relatively simple rules, Go is very complex, even more so than chess.Computers have only recently been capable of beating human masters.Have a look at the following for more details: https: // deepmind.com / research / alphago / Movement: Black
        plays first, with black and white taking turns.A stone can be placed at any unoccupied intersection of the board with limited exceptions.
        
        Suicide Rule: You cannot place a stone which will immediately have no liberties.
        
        KO Rule(EternityRule): Previous game states are not allowed. Keep a list of previous game states which must be checked before stones are placed https://youtu.be/JWdgqV-8yVg?t=7
        m35s. """

        print('Help')
        helpWindow = QDialog(self)
        tb = QTextEdit(helpWindow)
        tb.resize(350, 250)
        tb.setReadOnly(True)
        tb.setText(userGuide)
        tb.setAlignment(Qt.AlignLeft)
        helpWindow.setWindowTitle("Help")
        helpWindow.setFixedHeight(260)
        helpWindow.setFixedWidth(360)
        helpWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help = QtWidgets.QWidget()
    ui = Ui_Help()
    ui.setupUi(Help)
    Help.show()
    sys.exit(app.exec_())
